export const data = [
  { key: 'corona-virus-insurance', label: 'Corona Vírus Insurance', provider: 'FWD', color: '#d2691e', coverage: '12 months', price: '$ 1,200' },
  { key: 'car-insurance', label: 'Car Insurance', provider: 'FWD', color: '#d2691e', coverage: '15 months', price: '$ 1,100' },
  { key: 'car-ctpl-insurance', label: 'Car CTPL Insurance', provider: 'FWD', color: '#d2691e', coverage: '12 months', price: '$ 1,050' },
  { key: 'corona-virus-insurance', label: 'Corona Vírus Insurance', provider: 'AXA', color: '#3366ff', coverage: '13 months', price: '$ 1,250' },
  { key: 'car-insurance', label: 'Car Insurance', provider: 'AXA', color: '#3366ff', coverage: '15 months', price: '$ 1,110' },
  { key: 'property-insurance', label: 'Property Insurance', provider: 'AXA', color: '#3366ff', coverage: '18 months', price: '$ 1,150' },
  { key: 'corona-virus-insurance', label: 'Corona Vírus Insurance', provider: 'Dhipaya', color: '#99ff33', coverage: '10 months', price: '$ 1,600' },
  { key: 'car-insurance', label: 'Car Insurance', provider: 'Dhipaya', color: '#99ff33', coverage: '12 months', price: '$ 1,020' },
  { key: 'car-insurance', label: 'Car Insurance', provider: 'Thaisri', color: '#9e133d', coverage: '12 months', price: '$ 1,350' },
  { key: 'motorcycle-ctpl-insurance', label: 'Motorcycle CTPL Insurance', provider: 'Dhipaya', color: '#99ff33', coverage: '10 months', price: '$ 1,450' },
  { key: 'travel-insurance', label: 'Travel Insurance', provider: 'Bangkok Insurance', color: '#9eeef7', coverage: '10 months', price: '$ 1,250' },
  { key: 'car-insurance', label: 'Car Insurance', provider: 'Bangkok Insurance', color: '#9eeef7', coverage: '12 months', price: '$ 1,120' },
  { key: 'motorcycle-ctpl-insurance', label: 'Motorcycle CTPL Insurance', provider: 'Bangkok Insurance', color: '#9eeef7', coverage: '10 months', price: '$ 1,850' },
  { key: 'travel-insurance', label: 'Travel Insurance', provider: 'MSIG', color: '#ba1e2b', coverage: '10 months', price: '$ 1,050' },
];