import Head from 'next/head'
import { Container } from 'semantic-ui-react'
import Main from '../components/main/Main'
import '../styles/Home.module.css';

export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>Insurance Plans</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Main />
      </Container>
    </div>
  )
}
