import Head from 'next/head'
import Main from '../components/main/Main'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Insurance Plans</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main />
    </div>
  )
}
